# Generated by Django 5.2.6 on 2025-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_DB',
            fields=[
                ('Car_name', models.CharField(max_length=20)),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=20)),
                ('engine_model', models.CharField(max_length=20)),
                ('insurance_no', models.IntegerField()),
            ],
        ),
    ]
